name: Build Project

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache docker
        uses: actions/cache@v4
        with:
          path: ./.buildx-cache
          key: service-${{ runner.os }}-buildx-cache

      - name: Build Docker image with caching
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          cache-from: type=local,src=./.buildx-cache
          cache-to: type=local,dest=./.buildx-cache
          push: false

      - name: List Cargo Directory
        run: ls -la ~/.cargo/

      - name: List Target Directory
        run: ls -la target || echo "Target directory does not exist."
